Updated to build properly, 2012v1 released.

diff --git a/build/build b/build/build
--- a/build/build
+++ b/build/build
@@ -26,26 +26,27 @@ done
 
 {
 	read ver commitid
-} < <(head -1 ChangeLog | perl -ne "/^Version\\s*([\d\w]+)\\s*\(commit id ([\d\w-]+)\)$/ && print \"\$1 \$2\"")
+} < <(head -1 "$src_dir"/ChangeLog | perl -ne "/^Version\\s*([\d\w]+)\\s*\(commit id ([\d\w-]+)\)$/ && print \"\$1 \$2\"")
 
 echo "Top ChangeLog line interpreted as: version $ver, commit id $commitid"
 
 $skip_local_changes_check || {
-	head="$(git-rev-parse HEAD)" || die "cannot get a HEAD commit id"
+	head="$(git rev-parse HEAD)" || die "cannot get a HEAD commit id"
 	test "$head" == "$commitid" || die "wrong commit id (please fix ChangeLog to mention $head)"
 }
 
 test -d "$dist_dir" || mkdir -p "$dist_dir"
 
-test -z "$ver" && die "Error determining EclipseOSXRepackager version. Aborted."
+test -z "$ver" && die "Error determining EclipseOSXRepackager2012 version. Aborted."
 
 if test -z "$skip_zip"; then
-  zipfile="$dist_dir/EclipseOSXRepackager-v$ver.zip"
-	zipfolder="Eclipse OS X Repackager v$ver"
+  zipfile="$dist_dir/EclipseOSXRepackager2012-v$ver.zip"
+	zipfolder="Eclipse OS X Repackager 2012 v$ver"
 	dmgdir="$temp_dir/$zipfolder"
 	test -d "$dmgdir" && rm -r "$dmgdir"
 	mkdir -p "$dmgdir"
 	cp "$src_dir/EclipseOSXRepackager" "$dmgdir/"
+  perl -pi -e "s/\[\[ver\]\]/$ver/g" -- "$dmgdir/EclipseOSXRepackager"
   (cd "$temp_dir"; zip -r "$zipfile" "$zipfolder")
 	rm -rf "$dmgdir"
   echo "Created $zipfile."
@@ -54,21 +55,30 @@ fi
 test -z "$(which platypus)" && die "ERROR: Please install Platypus command-line tool (see http://sveinbjorn.org/platypus)"
 test -d "$cocoa_dialog" || die "CocoaDialog not found in $cocoa_dialog, please install or change the path inside this script"
 
-dmgdir="$temp_dir/Eclipse OS X Repackager v$ver"
+cp "$src_dir/EclipseOSXRepackager" "$temp_dir/"
+cp "$src_dir/EclipseOSXRepackagerUI" "$temp_dir/"
+perl -pi -e "s/\[\[ver\]\]/$ver/g" -- "$temp_dir/EclipseOSXRepackager"
+perl -pi -e "s/\[\[ver\]\]/$ver/g" -- "$temp_dir/EclipseOSXRepackagerUI"
+
+dmgdir="$temp_dir/Eclipse OS X Repackager 2012 v$ver"
 test -d "$dmgdir" && rm -r "$dmgdir"
 mkdir -p "$dmgdir"
 ln -s /Applications "$dmgdir/Applications"
 
-app="$dmgdir/Eclipse OS X Repackager.app"
+app="$dmgdir/Eclipse OS X Repackager 2012.app"
 test -d "$app" && rm -r "$app"
 
-platypus -FD -a "Eclipse OS X Repackager" -o None -p /bin/bash -V "$ver" -f "$src_dir/EclipseOSXRepackager" -f "$cocoa_dialog" -I org.andreyvit.EclipseOSXRepackager -c "$src_dir/EclipseOSXRepackagerUI" "$app" ||
+platypus -FDR -a "Eclipse OS X Repackager 2012" -p /bin/bash -V "$ver" \
+  -o None \
+  -f "$temp_dir/EclipseOSXRepackager" -f "$cocoa_dialog" \
+  -I eu.foxmoore.EclipseOSXRepackager2012 \
+  "$temp_dir/EclipseOSXRepackagerUI" "$app" ||
 	die "fatal: platypus failed."
 
 if test -z "$skip_zip"; then
-  dmgfile="$dist_dir/EclipseOSXRepackager-v$ver.dmg"
+  dmgfile="$dist_dir/EclipseOSXRepackager2012-v$ver.dmg"
   test -f "$dmgfile" && rm "$dmgfile"
-  "$src_dir/../create-dmg/create-dmg" --window-size 500 310 --background "$build_dir/background.gif" --icon-size 96 --volname "EclipseOSXRepackager-v$ver" --icon "Applications" 380 205 --icon "Eclipse OS X Repackager" 110 205 "$dmgfile" "$dmgdir"
+  "$build_dir/create-dmg/create-dmg" --window-size 500 310 --background "$build_dir/background.gif" --icon-size 96 --volname "EclipseOSXRepackager2012-v$ver" --icon "Applications" 380 205 --icon "Eclipse OS X Repackager 2012" 110 205 "$dmgfile" "$dmgdir"
   # hdiutil create -srcfolder "$dmgdir" "$dmgfile"
   echo "Created $dmgfile." 
 fi
